import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import createClient from "@/utils/supabase/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col flex-grow min-h-screen">
        <Header />
        <main className="flex justify-center items-center flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
